name: smartx_flutter_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.3
  firebase_auth: ^4.1.0
  flutter_facebook_auth: ^4.0.1
  google_sign_in: ^6.0.1
  image_picker: ^1.0.1
  carousel_slider: ^4.2.1
  shared_preferences: ^2.0.15
  google_maps_flutter: ^2.4.0
  dotted_border: ^2.0.0+3
  firebase_storage: ^11.2.5
  country_picker: ^2.0.20
  fluttertoast: ^8.2.2
  cached_network_image: ^3.2.3
  timeago: ^3.5.0
  flutter_spinkit: ^5.2.0
  firebase_messaging: ^14.6.5
  flutter_local_notifications: ^15.1.0+1
  http: ^1.1.0
  intl: 
  curved_navigation_bar: ^1.0.3
  geolocator: ^10.0.0
  permission_handler: ^10.4.3
  location: ^5.0.3
  rxdart: ^0.27.7
  share_plus: ^7.1.0
  screenshot: ^2.1.0
  path_provider: ^2.1.1
  utility_extensions:
    git:
      url: https://github.com/hamzali4642/utility_extensions




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/badges/
  fonts:
    - family: Worksans_Bold
      fonts:
        - asset: fonts/WorkSans-Bold.ttf
    - family: WorkSans_Medium
      fonts:
        - asset: fonts/WorkSans-Medium.ttf
    - family: WorkSans_Regular
      fonts:
        - asset: fonts/WorkSans-Regular.ttf
    - family: WorkSans_Semibold
      fonts:
        - asset: fonts/WorkSans-SemiBold.ttf  
    - family: WorkSans_Light
      fonts:
        - asset: fonts/WorkSans-Light.ttf  
